### ISSUE TITLE
Why FileVault 2 isn't working ?

### ISSUE THREAD

**Issue by jief666** [wmchris/DellXPS15-9550-OSX#116] opened 2019-09-12 19:03 UTC
Do you have an idea of the problem ?
Thanks.

**Comment by golimpio** [comment] 2019-09-13 01:28
I haven't enabled it, but check in the forum, someone have reported that it worked.

**Comment by krim404** [comment] 2019-09-26 15:45
any update?

**Comment by jief666** [comment] 2019-09-26 15:46
I don't have the XPS 15 yet, so can't tell...

**Comment by krim404** [comment] 2019-09-30 08:47
so, this was not a bug report but just a question? then i close it.

**Closed as completed by krim404** 2019-09-30 08:47 UTC

**Comment by lamhoangtung** [comment] 2021-04-08 14:56
I noticed that the README of BigSur tutorial no longer state FileVault 2 in the not working stuff ... Is this actually true ? @golimpio @wmchris

**Comment by golimpio** [comment] 2021-04-08 23:07
> I noticed that the README of BigSur tutorial no longer state FileVault 2 in the not working stuff ... Is this actually true ? @golimpio @wmchris

I haven't tested FileVault myself, so I don't know if it's working or not. I've seem people reporting that it was working for Catalina, but I'm not sure about Big Sur.

**Comment by golimpio** [comment] 2021-04-08 23:22
BTW, have anyone tried the steps for enabling FileVault in the Dortania guide?
- [https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html](https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html)

**Comment by krim404** [comment] 2021-04-10 08:47
it is working. using it right now

**Comment by lamhoangtung** [comment] 2021-04-13 14:09
Thanks for the confirmation
