### ISSUE TITLE
10.3.5 updated.  Thunderbolt 3  have some problem.  below details  help!!!!

### ISSUE THREAD

**Issue by Evan-tc** [wmchris/DellXPS15-9550-OSX#86] opened 2018-06-26 01:45 UTC
when shutdown the computer with  using Thunderbolt 3 ,  the computer will be restarted. 
if put out the using Thunderbolt 3 ,  the poweroff is normal.
![1](https://user-images.githubusercontent.com/40584291/41884330-7e7a6462-78e2-11e8-81e7-c92fb2e10594.png)
![2](https://user-images.githubusercontent.com/40584291/41884350-938f12ee-78e2-11e8-802d-b51b17665692.jpg)

**Comment by soulomoon** [comment] 2018-06-30 15:03
I have a sleep issue, if the computer try to sleep, it would stuck and finally trigger a kernel panic then restart , in the under scenario:
1 with type-c plugging in
2 menu bar showing 'pc card' with 'power off card' option(sleep is normal if 'power off card' is clicked, and `pc card` is disappeared from the menu, type-c device won't be affected though)
3 Have been asleep at least once after the system is turned on
![PC Card](https://i.imgur.com/uhZ32kA.png)

**Comment by krim404** [comment] 2018-07-01 23:07
tried it with the same hardware, cannot reproduce error.

**Comment by Evan-tc** [comment] 2018-07-02 01:43
now i updated the 10.4 beta MOJAVE,  the problem have been disappared. so amazing.

**Comment by soulomoon** [comment] 2018-07-02 11:11
I applied a workaround for my problem, hook an applescript powering off card to a sleepwatcher

**Comment by krim404** [comment] 2018-09-30 22:30
i'll close this ticket - mojave is live so no need to fix it anymore

**Closed as completed by krim404** 2018-09-30 22:30 UTC
