### ISSUE TITLE
[Dual Boot] Bluetooth does not work after rebooting from Mac OS 

### ISSUE THREAD

**Issue by Lukypie** [wmchris/DellXPS15-9550-OSX#26] opened 2017-05-13 18:41 UTC
In my system I got  three operating systems I've installed (in order) Windows, Mac OS, and Manjaro Linux.
The problems occurs when I cold start the PC from Mac OS and then rebooting into Linux, the bluetooth adapter stops working. Keeping rebooting does not solve the problem, and after rebooting to Mac OS the adapter still does not work. Booting to windows does not solve the problem.
The only thing I've not tried is to rebooting to Windows after the first boot to Mac OS.

Booting to Linux the first time and then to Mac OS does not cause any problem, even if I reboot twice, go to Mac OS and then back to linux. This happens **only when the first OS loaded is Mac OS**

If someone is guessing how I discovered this,  I use a bluetooth mouse lol 

Fix: Completely shutting down the PC.

Reproduceability: 80% 

dmesg from Linux when the problem occurs
[broken.zip](https://github.com/wmchris/DellXPS15-9550-OSX/files/998850/broken.zip)
![screenshot_20170513_204120](https://cloud.githubusercontent.com/assets/7904559/26028228/894a33d4-381c-11e7-8e56-c054c7d3e85a.png)

It happens especially when associating.
Can't explain the reason, sometimes it happens, other times no.

**Comment by Lukypie** [comment] 2017-05-13 18:43
Look at that 4.209212, that is my adapter name from Mac OS lol....So I think it can be a bluetooth kext bug, since it is supported natively, what can we do?

**Comment by wmchris** [comment] 2017-05-15 11:43
tbh i cant reproduce your bug. i get BT to work with Ubuntu, OSX and Win every time :/

**Comment by wmchris** [comment] 2017-06-19 06:27
any news on this issue?

**Comment by Lukypie** [comment] 2017-06-22 12:32
I don't know honestly, I think that is just a Linux driver bug which can't power on the device when it is initialized in another OS, the only way to fix is a complete shutdown, I don't know that much about PCI devices
This happens also when the first boot is Windows, so Mac OS isn't the main problem here. 
Maybe this can be due to the different behaviour of those drivers.

**Comment by ghost** [comment] 2017-11-15 01:31
@Lukypie I am pretty sure this is a bug with Archlinux. If you check that wiki page online under setting Bluetooth. They stated that in order to get Bluetooth to work with MacOs and archlinux, you must first remove the device from macOs then boot into Archlinux. I have Archlinux and macOs on my XPS and it works fine Everytime I remove the device from macOs and then getting connected with archlinux

**Comment by krim404** [comment] 2018-09-30 22:28
i'll close this ticket for now.

**Closed by krim404** 2018-09-30 22:28 UTC
